# Generated by Django 3.2.25 on 2024-05-25 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typing_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='TypingText',
            options={'permissions': [('can_add_text', 'Can add typing text'), ('can_change_text', 'Can change typing text')]},
        ),
    ]
